url: http://joluper.github.io
baseurl: /

# Site Settings
title: José Luis Pérez Portfolio
description: "Este es mi portfolio, aquí podrás encontrar información profesional sobre mi."
keywords: "joluper, jekyll, portfolio"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
